//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public int emp_No { get; set; }
        public string emp_name { get; set; }
        public string emp_mobile { get; set; }
        public string emp_email { get; set; }
        public Nullable<int> emp_role_id { get; set; }
        public Nullable<int> emp_isvalid { get; set; }
        public string emp_workaddress { get; set; }
        public Nullable<System.DateTime> emp_jointime { get; set; }
        public Nullable<System.DateTime> emp_quit { get; set; }
        public Nullable<int> emp_dept_id { get; set; }
        public string emp_post { get; set; }
        public string emp_pwd { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
