//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow
    {
        public int Work_Id { get; set; }
        public string Work_Title { get; set; }
        public string Work_Content { get; set; }
        public Nullable<int> Work_EmpNo { get; set; }
        public Nullable<int> Work_DeptId { get; set; }
        public Nullable<System.DateTime> Work_CreateTime { get; set; }
        public Nullable<int> Work_Status { get; set; }
        public Nullable<int> Work_ApproverNo { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
